variable "resource_group_name" {
  description = "Name of the resource group name that contains ARO"
}

variable "cluster_name" {
  description = "Name of the ARO cluster"
}

variable "region" {
  description = "Location of the resource group."
}

variable "generate_kube_config" {
  default = false   # kube config file will NOT be generated by default
  description = "Dictates if the kubeConfig file should be generated or not"
}

# Either this or the 'kube_config_path' variable will be used for kubeConfig
variable "kube_config_contents" {
  default = "EMPTY"   # invalid contents by default
  description = "KubeConfig file contents"
}

variable "client_secret" {
  description = "AzureAD application password - also known as client secret"
}

variable "client_id" {
  description = "AzureAD application id - also known as client id"
}

variable "tenant_id" {
  description = "Azure subscription tenant id"
}

variable "cluster_url" {
  description = "ARO cluster host url"
}

#variable "kube_config_path" {
#  default = "/tmp/kubeconfig"
#  description = "Location from where kubeConfig will be read"
#}

variable "client_certificate_path" {
  default = "/tmp/aro-cluster-client.crt"
  description = "Location of client certificate for ARO cluster"
}

variable "client_key_path" {
  default = "/tmp/aro-cluster-client.key"
  description = "Location of client key for ARO cluster"
}

variable "ca_certificate_path" {
  default = "/tmp/aro-cluster-ca.crt"
  description = "Location of ca certificate for ARO cluster"
}
